import { format } from 'date-fns'

export function formatCurrency(value: number, currency = 'USD', locale = 'en-US') {
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency,
  }).format(value)
}

export function formatDate(date: string | number | Date, pattern = 'PPP') {
  return format(new Date(date), pattern)
}

export function debounce<T extends (...args: any[]) => any>(
  fn: T,
  delay: number
): (...args: Parameters<T>) => void {
  let timeoutId: ReturnType<typeof setTimeout>
  return (...args: Parameters<T>) => {
    clearTimeout(timeoutId)
    timeoutId = setTimeout(() => fn(...args), delay)
  }
}

/**
 * Resolves local, relative, proxy, and absolute image URLs safely.
 */
export function resolveImageUrl(pathOrUrl?: string | null): string | null {
  if (!pathOrUrl) return null
  const trimmed = String(pathOrUrl).trim()
  if (!trimmed) return null

  // Data URIs or Blob URLs
  if (trimmed.startsWith('data:image') || trimmed.startsWith('blob:')) {
    return trimmed
  }

  // Handle port missing on localhost URLs generated by default config
  if (trimmed.startsWith('http://localhost/storage/') || trimmed.startsWith('http://127.0.0.1/storage/')) {
    return trimmed.replace('http://localhost/', 'http://localhost:8000/').replace('http://127.0.0.1/', 'http://localhost:8000/')
  }

  // Already a full remote URL (CDN/S3/external)
  if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) {
    return trimmed
  }

  // Relative storage path (e.g. 'products/xxx.jpg' or '/storage/products/xxx.jpg')
  const cleanPath = trimmed.startsWith('/') ? trimmed : `/${trimmed}`
  if (cleanPath.startsWith('/storage/')) {
    return `http://localhost:8000${cleanPath}`
  }

  return `http://localhost:8000/storage${cleanPath}`
}
